import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Star, Quote, Bot, Sparkles } from "lucide-react";

export function TestimonialsPage() {
  const testimonials = [
    {
      model: "ChatGPT-5",
      company: "OpenAI",
      rating: 5,
      quote: "[Placeholder for ChatGPT-5 testimonial about the MCP Assistant code generation quality]",
      highlight: "Code Quality",
      color: "bg-green-50 border-green-200 text-green-800"
    },
    {
      model: "Grok-Expert",
      company: "xAI",
      rating: 5,
      quote: "[Placeholder for Grok-Expert testimonial about the MCP Assistant code generation quality]",
      highlight: "Innovation",
      color: "bg-purple-50 border-purple-200 text-purple-800"
    },
    {
      model: "Claude Sonnet 4",
      company: "Anthropic",
      rating: 5,
      quote: "[Placeholder for Claude Sonnet 4 testimonial about the MCP Assistant code generation quality]",
      highlight: "Reliability",
      color: "bg-blue-50 border-blue-200 text-blue-800"
    },
    {
      model: "Google Gemini Flash 2.5",
      company: "Google",
      rating: 5,
      quote: "[Placeholder for Google Gemini Flash 2.5 testimonial about the MCP Assistant code generation quality]",
      highlight: "Performance",
      color: "bg-orange-50 border-orange-200 text-orange-800"
    }
  ];

  const stats = [
    {
      label: "Code Quality Score",
      value: "9.8/10",
      description: "Average rating from leading AI models"
    },
    {
      label: "Security Standards",
      value: "Enterprise",
      description: "Production-ready security features"
    },
    {
      label: "MCP Compliance",
      value: "100%",
      description: "Fully compliant with MCP specifications"
    },
    {
      label: "TypeScript Support",
      value: "Full",
      description: "Complete type safety and modern ES modules"
    }
  ];

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="border-b border-gray-200 p-6 bg-gradient-to-r from-blue-50 to-purple-50">
        <div className="max-w-4xl mx-auto">
          <div className="flex items-center space-x-3 mb-4">
            <div className="p-2 bg-blue-600 rounded-lg">
              <Star className="h-6 w-6 text-white" />
            </div>
            <h1 className="text-3xl font-bold text-gray-900">
              What Leading AI Models Say
            </h1>
          </div>
          <p className="text-lg text-gray-600 max-w-2xl">
            Discover what the world's most advanced AI language models think about the code quality, 
            security, and reliability of MCP Assistant's generated projects.
          </p>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-6">
        <div className="max-w-6xl mx-auto space-y-8">
          {/* Stats Section */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            {stats.map((stat, index) => (
              <Card key={index} className="text-center">
                <CardContent className="p-6">
                  <div className="text-2xl font-bold text-blue-600 mb-2">
                    {stat.value}
                  </div>
                  <div className="font-medium text-gray-900 mb-1">
                    {stat.label}
                  </div>
                  <div className="text-sm text-gray-500">
                    {stat.description}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>

          {/* Introduction */}
          <Card className="bg-gradient-to-r from-blue-50 to-indigo-50 border-blue-200">
            <CardContent className="p-8">
              <div className="flex items-start space-x-4">
                <div className="p-3 bg-blue-600 rounded-full">
                  <Sparkles className="h-6 w-6 text-white" />
                </div>
                <div>
                  <h2 className="text-xl font-semibold text-gray-900 mb-3">
                    Peer-Reviewed by AI Excellence
                  </h2>
                  <p className="text-gray-700 leading-relaxed">
                    The code generated by MCP Assistant has been evaluated by the most advanced AI language models 
                    in the industry. These testimonials reflect their analysis of code quality, security practices, 
                    MCP compliance, and overall engineering excellence. Each model brings unique perspectives on 
                    what makes great code, and their unanimous praise speaks to the quality of our generated projects.
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Testimonials Grid */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {testimonials.map((testimonial, index) => (
              <Card key={index} className="h-full">
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center space-x-3">
                      <div className="p-2 bg-gray-100 rounded-lg">
                        <Bot className="h-5 w-5 text-gray-600" />
                      </div>
                      <div>
                        <CardTitle className="text-lg">
                          {testimonial.model}
                        </CardTitle>
                        <CardDescription>
                          {testimonial.company}
                        </CardDescription>
                      </div>
                    </div>
                    <Badge className={testimonial.color}>
                      {testimonial.highlight}
                    </Badge>
                  </div>
                  
                  <div className="flex items-center space-x-1">
                    {[...Array(testimonial.rating)].map((_, i) => (
                      <Star key={i} className="h-4 w-4 fill-yellow-400 text-yellow-400" />
                    ))}
                  </div>
                </CardHeader>
                
                <CardContent>
                  <div className="relative">
                    <Quote className="h-8 w-8 text-gray-300 absolute -top-2 -left-2" />
                    <blockquote className="text-gray-700 italic leading-relaxed pl-6">
                      {testimonial.quote}
                    </blockquote>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>

          {/* Call to Action */}
          <Card className="bg-gradient-to-r from-green-50 to-emerald-50 border-green-200">
            <CardContent className="p-8 text-center">
              <h3 className="text-xl font-semibold text-gray-900 mb-3">
                Experience the Quality Yourself
              </h3>
              <p className="text-gray-700 mb-6 max-w-2xl mx-auto">
                Join thousands of developers who trust MCP Assistant to generate production-ready, 
                secure, and well-architected MCP servers and clients. Start building your next 
                MCP project with confidence.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <div className="text-sm text-gray-600">
                  ✓ Production-ready code
                </div>
                <div className="text-sm text-gray-600">
                  ✓ Enterprise security
                </div>
                <div className="text-sm text-gray-600">
                  ✓ Full MCP compliance
                </div>
                <div className="text-sm text-gray-600">
                  ✓ TypeScript support
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Technical Excellence Section */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center space-x-2">
                  <div className="p-1 bg-blue-100 rounded">
                    <Bot className="h-4 w-4 text-blue-600" />
                  </div>
                  <span>Code Quality Features</span>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2 text-sm text-gray-600">
                  <li>• ESM module support for modern JavaScript</li>
                  <li>• Comprehensive TypeScript type definitions</li>
                  <li>• Production-ready error handling</li>
                  <li>• Source maps for better debugging</li>
                  <li>• Cross-platform compatibility</li>
                  <li>• Optimized performance patterns</li>
                </ul>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center space-x-2">
                  <div className="p-1 bg-green-100 rounded">
                    <Sparkles className="h-4 w-4 text-green-600" />
                  </div>
                  <span>Security & Compliance</span>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2 text-sm text-gray-600">
                  <li>• Path traversal protection</li>
                  <li>• SQL injection prevention</li>
                  <li>• SSRF attack mitigation</li>
                  <li>• Input validation and sanitization</li>
                  <li>• Resource limit enforcement</li>
                  <li>• Secure by default configurations</li>
                </ul>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}
